theme = "aura"

[editor]
auto-save	= true
auto-format	= true
line-number = "absolute"
middle-click-paste = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true
display-inlay-hints	= true

[editor.indent-guides]
render = false
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
tab = ":format"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
"ret" = "goto_word"
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-d" = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]
C-g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

[keys.normal.space]
tab = "goto_last_accessed_file"
F = "file_picker_in_current_buffer_directory"

[keys.select]
"C-d" = ["search_selection", "extend_search_next"]
